### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by vigji** [PeyracheLab/pynapple#101]
Discussing how to setup a PR for GitHub Actions testing.

My normal configuration would include 
 - linting
 - testing with `pytest`

To set it up, I wanted to know your take on linting. I normally use and highly recommend [`black`](https://github.com/psf/black), [`flake8`](https://flake8.pycqa.org/en/latest/), and [`isort`](https://github.com/PyCQA/isort) for code consistency and some checks on potentially hanging parts. Adopting them would mean running them and potentially making cosmetic changes in many files, would you be ok with that?

**Comment by gviejo** [comment]
Hey Luigi

I think your recommendations are good. I am ok for the cosmetic changes.
Could you send me your setup files so I can test them.
Thank you

Guillaume
