### ISSUE TITLE
subselecting TsGroup using a list of indices

### ISSUE THREAD

**Issue by samdeoxys1** [PeyracheLab/pynapple#112]
Given a TsGroup, I could do `spike_trains[[1,2]]` to subselect the TsGroup spike_trains, however doing `spike_trains[[2,1]]` gives the error: 
<img width="757" alt="image" src="https://user-images.githubusercontent.com/64565475/196551795-7badc4cf-2fe5-42dc-a9f0-9c1e23f361e5.png">

Is this to be expected? I would expect there to be more flexibility in subselecting a TsGroup.

**Comment by gviejo** [comment]
Hello Sam, 
Yes it's a safety feature. Because you need to index both the meta data and the ts group. So it's better to keep the same order of keys.
Hope this help,
Guillaume
