### ISSUE TITLE
object metadata name vs prettytable name

### ISSUE THREAD

**Issue by SaraMati** [PeyracheLab/pynapple#113]
currently object metadata name is shown in prettytable format that does not necessarily match the actual name (as in ._metadata method). so when the user wants to use .get_info for example, or .getby_category they will look at the object and try to call .get_info by the pretty table column name which throws an error

e.g. 
.get_info('Freq. (Hz)') 
.get_info('freq')

either put a docstring that refers to the true metadata names or match the names everywhere

**Comment by gviejo** [comment]
Solved in 4c3090d743848e0cb6fc56bd7b854785859673aa
