### ISSUE TITLE
Description return of function compute_crosscorrelogram

### ISSUE THREAD

**Issue by javierzsm** [PeyracheLab/pynapple#119]
Hi, 
I am trying to figure the exact content of the DataFrame returned by the function compute_crosscorrelogram.
I couldn't find it in the Docs. Is there a place where I can find this description? 
Thanks!
Javier

**Comment by gviejo** [comment]
Hi Javier, 

You can find a good description of the algorithm for computing cross-correlogram here :
https://www.med.upenn.edu/mulab/crosscorrelation.html

**Comment by javierzsm** [comment]
Hi,
Thank you very much for your answer. It is indeed instructive. However, my question was more on the actual format of the return, but I think it's solved. I was confused by the use of multiindexed dataframe for the output. My bad.
Thank you very much!
