### ISSUE TITLE
Spatial Info and Tuning Curves (continuous and spike data)

### ISSUE THREAD

**Issue by dlevenstein** [PeyracheLab/pynapple#19]
Hey - looking to compute spatial info and place fields for continuous time data (in this case, activations from a simulated neural network, but could also work for e.g. calcium data). Does this already exist in pynapple? If not, will make the functions.

Looks like computeSpatialInfo is only for a 1D angular variable (HD) and computePlaceFields is for spikes, right?

**Comment by gviejo** [comment]
Hey Dan, spatial_info is only for HD right now in functions.py and hasn't been tested yet within pynapple.
So far, computePlaceFields works with spikes but feel free to work on the function for continous data. If you want some inspirations, you can take a look [here](https://github.com/gviejo/PSBImaging/blob/main/python/functions.py). It is my repository to work with calcium data and it takes continous data as input.

**Comment by dlevenstein** [comment]
Functiosn: 1D Tuning Curve, 2D tuning curve, ND tuning curve.

East: for continuous (tsd) or spike (ts) data

**Comment by dlevenstein** [comment]
as part of this, ran into #29 re: bin standardization

Related: these functions have nb_bins as a scalar input, which produces a square shaped discretization of space. However, many spaces might be longer than they are wide. Maybe we should have the option to put in a (length, width) touple, which if an integer nb_bins is passed in is converted to (nb_bins, nb_bins)?

**Comment by dlevenstein** [comment]
I noticed computePlaceFields saves place_fields as a dictionary of pd.DataFrames, would this be better as a pd.Panel?

**Comment by gviejo** [comment]
It says Deprecated since version 0.20.0. I would suggest return a dictionnary then. Or eventually a 3d array.

**Comment by dlevenstein** [comment]
Ah bummer. Dictionary probably better... to maintain cellID labels (similar to TSGroup)

**Comment by gviejo** [comment]
Added in 9d8ad62e8d46545351472cdb15e8af338ef91907
