### ISSUE TITLE
Rate function

### ISSUE THREAD

**Issue by SaraMati** [PeyracheLab/pynapple#2]
- this can have options to generate "count" which is binned spike train or "rate" 
We should decide whether user can
- specify bins: regular bins, Gaussian or box-car bins 
or
- smooth after

**Comment by dlevenstein** [comment]
In the case of multiple spike trains, should apply to TsGroup (#18)

**Comment by apeyrache** [comment]
Ideally, I would not use the word "Spike" in it, as it could potentially be anything. I've used it with ripples times in the past.
So just "TimeBinning"?

**Comment by dlevenstein** [comment]
Yes. I think to make as general as possible -  it should just bin and return the counts. Basically the most general way to convert a ts object to a tsd object. Everything else can be done afterwards.

**Comment by dlevenstein** [comment]
^^^^ in which I realize that this is just a call to histogram.

**Comment by dlevenstein** [comment]
Solved with Ts.count/Tsd.count/TsGroup.count by @gviejo 🙌
