### ISSUE TITLE
pyqt5 compatibility with Spyder

### ISSUE THREAD

**Issue by dlevenstein** [PeyracheLab/pynapple#38]
new pynapple install updates pyqt5 to 5.15.6, but spyder requires pyqt5<5.13. Is it possible to use an earlier version of pyqt?

Alternatively - does anyone recommend a IDE similar to spyder?

**Comment by dlevenstein** [comment]
I reinstalled with 'pyqt5<5.13' in the setup.py. Will let you know if I run into any issues.

**Comment by gviejo** [comment]
Hey Dan, if you want to know about the compatibility, you can do a 
`nap.load_session()` in your terminal or `nap.load_session(path,'neurosuite')` if you have somewhere a session processed with neurosuite data. If the GUI open, it should be good.

**Comment by gviejo** [comment]
Hey Dan, any news on that? I am curious to know. If it worked, let me know so I can close the issue.

**Comment by gviejo** [comment]
Ok if you need some neurosuite data, there is the [test data](https://www.dropbox.com/s/1kc0ulz7yudd9ru/A2929-200711.tar.gz?dl=1) for pynapple 

For my IDE, I use sublime text (with the packages terminus and sendcode to integrate the ipython terminal within it).
