### ISSUE TITLE
compute_2d_tuning_curve returns doc

### ISSUE THREAD

**Issue by dlevenstein** [PeyracheLab/pynapple#46]
compute_2d_tuning_curve documentation states that it returns a numpy array:

 Returns
    -------
    numpy.ndarray
        Stacked array of the tuning curves with dimensions (n, nb_bins, nb_bins).
        n is the number of object in the input group. 
    list
        bins center in the two dimensions

but the function actually returns a dictionary.

**Comment by gviejo** [comment]
Thanks Dan, I will change it. It returns a numpy array and the bins position.
This is the way to call it :
```
tcurves2d, binsxy = nap.compute_2d_tuning_curves(group=ts_group,
                                                 feature = features,
                                                 ep = epoch,
                                                 nb_bins=10)
```

**Comment by dlevenstein** [comment]
I'm wondering if we want to default ep=feature.time_support, or if it's best to force the user to put this in?

Another issue while updating the continuous code: 
I'd love to use 
`groups_value[c] = pd.cut(groups_value[c],binsxy[c])' to digitize the feature values, but pd.cut throws an error when called on a Tsd

**Comment by gviejo** [comment]
I think you are right. For some functions, we can give the epoch as an option and use the time support as default.
