### ISSUE TITLE
value_from time support bug - exclusive of lower bound

### ISSUE THREAD

**Issue by dlevenstein** [PeyracheLab/pynapple#47]
When calling:

`x = nap.Tsd(t = np.arange(5), d=np.arange(5),time_units='s')`
`y = nap.Tsd(t = np.arange(5), d=np.arange(5),time_units='s')`
`x_yvalue = x.value_from(y,y.time_support)`

x_yvalue is missing the first time point (t=0), even though the time support of y is from 0 to 4.

This results in a number of issues when you expect things to line up because they have the same time support, but the first timepoint is dropped

**Comment by dlevenstein** [comment]
Fixed by adding 
`include_lowestbool = True`

 to the call to pd.cut in interval_set.in_interval

let me know if you want to keep this and I'll pull it in with my PR

**Comment by apeyrache** [comment]
OK we have to be careful with that. The problem is that you cannot in theory include both bounds, otherwise, a ts [0 1 2] restricted on intervalsets [0 1] [1 2] will output 4 values.
Of course, the intervalset should be 0 0.9999999999 [1 1.999999999] but no one will ever define it this way.
what do you think?

**Comment by dlevenstein** [comment]
Hm, not sure. I definitely think the initial behavior is problematic (i.e. with time support not being inclusive). Maybe there's a better way to deal with it.

**Comment by apeyrache** [comment]
should we decrease the lower bound of time_support by 1us by default?

**Comment by apeyrache** [comment]
I agree with you that a ts/tsd restricted on its own time_support should output the same object!!

**Comment by dlevenstein** [comment]
decreasing by default seems like it might make some issues, like crawling down my 1us every time its redefined

**Comment by dlevenstein** [comment]
We definitely don't want double counting with interval sets too.

**Comment by dlevenstein** [comment]
Note that pd.cut include_lowest only impacts the first interval. But this could still cause problems say with loops over adjacent intervals.

https://pandas.pydata.org/docs/reference/api/pandas.cut.html

**Comment by apeyrache** [comment]
OK, so what is really important is that restricting to time_support gives  the same output. Is the problem the first interval or any lower bound (in the case time_support is composed of several sub-itnervals)? 
Also, it should not be allowed to have a time support [1 2] [2 3], because this can also lead to weird results, An easy solution would be to merge close intervals at the us resolution any time time_support is updated.

**Comment by dlevenstein** [comment]
Basically, this should not happen 😂: 

<img width="324" alt="Screen Shot 2022-01-20 at 6 52 07 PM" src="https://user-images.githubusercontent.com/7265688/150440529-1f83d060-ed21-433e-8af4-a2362f4d52c1.png">


<img width="306" alt="Screen Shot 2022-01-20 at 6 53 51 PM" src="https://user-images.githubusercontent.com/7265688/150440692-d784b0fa-8ae3-49ac-91ad-79ce80cf1a3e.png">

**Comment by dlevenstein** [comment]
Strangely, adding include_lowest=true to IntervalSet.in_interval fixes the first one, but not the second one. Guess I need to look more into value_from.....

<img width="299" alt="Screen Shot 2022-01-20 at 6 54 40 PM" src="https://user-images.githubusercontent.com/7265688/150440773-ca4b7cfd-34be-462e-884c-4ee57da4eb85.png">

**Comment by dlevenstein** [comment]
Oh, it's because of this:
Restricting a Tsd to its own time_support drops the first value.
This is weird to me because restrict uses a call to IntervalSet.in_interval... so include_lowest=True should pass through?


<img width="257" alt="Screen Shot 2022-01-20 at 7 02 00 PM" src="https://user-images.githubusercontent.com/7265688/150441374-056d6e1b-39c1-459e-8533-b3bebad42810.png">

**Comment by dlevenstein** [comment]
Oh, this has to do with the behavior of declaring a new Tsd. (i.e. which is done at the output of restrict)

 here's an example that shows the issue:
<img width="349" alt="Screen Shot 2022-01-20 at 7 12 12 PM" src="https://user-images.githubusercontent.com/7265688/150442244-4d9b0a39-8438-416c-8082-0e0c189a03b8.png">


If I make a new Tsd from y, with the time_support y.time_support, the first timestamp is lost

**Comment by dlevenstein** [comment]
Of course, with include_lowest, you have weird behavior like this:

<img width="384" alt="Screen Shot 2022-01-20 at 7 21 12 PM" src="https://user-images.githubusercontent.com/7265688/150443019-78b39e39-653d-4b1e-94bf-3963b74625e7.png">


The first interval is inclusive of the 0 timepoint, but the second interval [3 4] is not inclusive of 3 🤦‍♂️

**Comment by gviejo** [comment]
Solved in a82a077d167996d9f9753ad0ef263d454dad32b5
One microsecond is removed to a start time in the construction of an IntervalSet only if the start is equal to the next end. 
And bins are closed so it's [start1 end1] [start2 end2].
