### ISSUE TITLE
pd.cut with Tsd bug

### ISSUE THREAD

**Issue by dlevenstein** [PeyracheLab/pynapple#48]
Calling pd.cut on a Tsd throws an error

`x = nap.Tsd(t = np.arange(5), d=np.arange(5),time_units='s')`
`pd.cut(x,[0,2,4])`

Raises ValueError: Cannot cast interval[int64, right] dtype to float64

Something to do with a call to TimeUnits.format_timestamps

**Comment by gviejo** [comment]
Hum it should probably not. It's calling a pandas function so it's probably best practice to transform it to a pandas series.
What can work is ```pd.cut.(x.as_units('s'), [0, 2, 4])```.

Let me know if it's a huge issue or not because I can't think of a way to solve this right now.

**Comment by dlevenstein** [comment]
Not a huge issue. I guess the question is basically if we want the user to be able to use the pandas functions that are inherited. Might be too much work for now.
