### ISSUE TITLE
decode without occupancy normalization

### ISSUE THREAD

**Issue by dlevenstein** [PeyracheLab/pynapple#49]
decode__1d and decode_2d should allow for feature=None, for conditions where you don't have, or don't want to bias by behavioral occupancy for decoding.

For example:
-sleep
-an open field experiment, where tuning curves are extracted from random foraging (full occupancy), but then experiment is done on navigation to remembered goal locations (limited occupancy)

**Comment by gviejo** [comment]
Solved in 9d8ad62e8d46545351472cdb15e8af338ef91907
