### ISSUE TITLE
non-overlapping boundaries in intervalset

### ISSUE THREAD

**Issue by apeyrache** [PeyracheLab/pynapple#52]
at construction, overlapping segments should be merged (and a warning be thrown)
segments with common boundaries should be closed, i.e. e.g. [0 1[ [1 2]) should be replaced by [0 1-eps] [1 2] (this would throw a warning as well)

**Comment by gviejo** [comment]
Solved in a82a077d167996d9f9753ad0ef263d454dad32b5
