### ISSUE TITLE
Problem creating an environment 

### ISSUE THREAD

**Issue by GRVite** [PeyracheLab/pynapple#60]
I cannot create a functional environment from the environment.yml file

conda version : 4.10.3
conda-build version : 3.18.11
python version : 3.7.6.final.0
virtual packages : __osx=10.16=0
                __unix=0=0
                __archspec=1=x86_64

**Comment by GRVite** [comment]
How was the environment of the file exported?

**Comment by gviejo** [comment]
Solved in a3fd8a2363dc259e27a352daa90c6172507163fd
