### ISSUE TITLE
Use of neurosuite methods

### ISSUE THREAD

**Issue by GRVite** [PeyracheLab/pynapple#67]
For using the neurosuite methods you need to call the class Neurosuite inside the file neurosuite, like:
pynapple.neurosuite.NeuroSuite.method
but it should be just pynapple.neurosuite.method

**Comment by gviejo** [comment]
if you do a data = nap.load_session(folder_path), all the methods the class Neurosuite are accessible through data like
data.load_meanwaveforms

**Comment by GRVite** [comment]
Alright, now I notice the confusion (;
