### ISSUE TITLE
PyQt error with spyder

### ISSUE THREAD

**Issue by GRVite** [PeyracheLab/pynapple#68]
I had this error with running spyder in the pynapple environment

Class RunLoopModeTracker is implemented in both /anaconda3/lib/python3.7/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x117d8e270) and /anaconda3/lib/libQt5Core.5.dylib (0x11fabda80). One of the two will be used. Which one is undefined.

spyder 5.2.2
conda 4.10.3
python 3.9

**Comment by GRVite** [comment]
For some reason, installing spyder with conda makes it incompatible with PyQt. I created a new environment from scratch and I installed it with pip, and I no longer had that error.

**Comment by dlevenstein** [comment]
This is weird. I had the same issue. Is there something we can do (either in the doc, or in the dependencies) so future users don't have this issue or are aware of the workaround?

I had to change my version of PyQt and various dependencies (see #38)

**Comment by GRVite** [comment]
Yes, we should do something about it. What were the steps you took?

**Comment by dlevenstein** [comment]
(feel free to assign me so its on my to do list)

**Comment by gviejo** [comment]
Is there something happening on this issue or can I close it?
