### ISSUE TITLE
decode2d with TsdFrame broken

### ISSUE THREAD

**Issue by dlevenstein** [PeyracheLab/pynapple#69]
Somehow my update to decode_2d has been reverted, so it no longer works with TsdFrame input?

**Comment by dlevenstein** [comment]
related: decode_2d expects tuning_curves to have tuning_curves.keys()...

but 2d tuning curves from compute_2d_tuning_curves_continuous are a Numpy array

**Comment by gviejo** [comment]
Do we agree there should be a linear decoder that can take all types of input?

**Comment by dlevenstein** [comment]
definitely 👍

**Comment by dlevenstein** [comment]
Though, do we want to reimplement the wheel? https://github.com/KordingLab/Neural_Decoding

**Comment by gviejo** [comment]
no I would just implement the linear decoder. Things like xgb will create dependencies.

**Comment by gviejo** [comment]
You are thinking right :laughing:

**Comment by gviejo** [comment]
I am opening a new issue title "Implementing linear decoder".
