### ISSUE TITLE
Warning when oppening a TS

### ISSUE THREAD

**Issue by GRVite** [PeyracheLab/pynapple#74]
It happened after using the function pyna.load_session.

time_series.py:122: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  super().__init__(index=t, data=d)

**Comment by gviejo** [comment]
I corrected it in the latest commit. Did you try to pull it?

**Comment by gviejo** [comment]
fixed in latest commits
