### ISSUE TITLE
How to load .lfp file without clu/res

### ISSUE THREAD

**Issue by dlevenstein** [PeyracheLab/pynapple#78]
Currently the only way to load .lfp is with a neurosuite object, which fails if there's no clu/res files in the base path.

**Comment by dlevenstein** [comment]
Temporary fix:

`
from pynapple.io.neurosuite import NeuroSuite

data_directory = '/Users/dl2820/Dropbox/research/Datasets/20140526_277um'

class NSObj(NeuroSuite):
    def __init__(self,path):
        self.path = path
        return
      
nsobj = NSObj(data_directory)
lfp = nsobj.load_lfp(extension='lfp',channel=0)
`

**Comment by gviejo** [comment]
I added a standalone function for this :
http://127.0.0.1:8000/io/#pynapple.io.misc.load_eeg

Could you test it and let me know if I can close the issue?

**Comment by gviejo** [comment]
IT's basically :
```
import pynapple as nap
lfp = nap.load_eeg('mypath/to/file.lfp', channel=0)
```
