### ISSUE TITLE
Suggestion: Add the processed pynapple NWB to A2929-20071 example

### ISSUE THREAD

**Issue by seankmartin** [PeyracheLab/pynapple#87]
Hi,

Thanks for sharing the repository 😄 

I was trying to run the [quick start](https://peyrachelab.github.io/pynapple/notebooks/pynapple-quick-start/) and I ran into some difficulty with setting up the NWB through the GUI at the `nap.load_session` step.
I figured it out from the [IO docs](https://peyrachelab.github.io/pynapple/notebooks/pynapple-io-notebook/) but I think for a quick start the example compressed folder [provided here](https://www.dropbox.com/s/1kc0ulz7yudd9ru/A2929-200711.tar.gz?dl=1) should contain the pynapple nwb file already for simplicity.

Then maybe in the [IO docs](https://peyrachelab.github.io/pynapple/notebooks/pynapple-io-notebook/) you could instruct the user to delete the NWB file for the purposes of the tutorial (or facilitate a create_new_nwb or similar argument to load_session).

Best,
Sean

**Comment by gviejo** [comment]
Thank you Sean for your suggestion. I will generate two datasets (one with the nwb and one without the nwb) and make it more clear in the readme.

Best
Guillaume

**Comment by gviejo** [comment]
Solved in 372403f712e52a766c6e5748ba1969f151ea42dd

Let us know if you have other suggestions.

**Comment by seankmartin** [comment]
Great, thanks Guillaume, will do
