### ISSUE TITLE
loading neurosuite data

### ISSUE THREAD

**Issue by macamu1988** [PeyracheLab/pynapple#99]
First, thank you for this great tool!
I am having problems loading my neurosuite data. Everytime I try to load my data i get the same error message: "ValueError: id 12 already in the table"
Do you know what could it be? I have two regions one with spikes (tetrode) and other without spikes (single wires). May this be the reason?
Thank you so much!
Best
![Screenshot from 2022-06-30 13-57-09](https://user-images.githubusercontent.com/45079922/176747286-98098e8d-03d5-4bb9-8ab4-f67180f8514e.png)
![Screenshot from 2022-06-30 13-57-59](https://user-images.githubusercontent.com/45079922/176747288-e99ccb3a-ab00-46d4-afa9-11776645cbe1.png)
![Screenshot from 2022-06-30 14-28-22](https://user-images.githubusercontent.com/45079922/176751549-6f47af5a-0aa9-4e5b-952a-a14c1de27b8f.png)

**Comment by gviejo** [comment]
Hello, 

I believe it's a probleme of the uniqueness of electrode identity within the NWB file. 

Could you try to load it again but deleting the temp.clu.1 first? To load it again, you have to delete the pynapplenwb folder first.

Also if you don't have a clu.2 it might be good to delete all the res.2, fet.2, spk.2.

**Comment by macamu1988** [comment]
Hi Guillaume, thanks for your answer. It is completely my bad. I was introducing the channel id 12 twice! Sorry about it! now it works perfectly! :)
thank you!

**Comment by gviejo** [comment]
Glad to hear that. Enjoy pynappling.
